[package]
name = "fundu"
version = "0.3.0"
edition = "2021"
authors = ["Joining7943 <joining@posteo.de>"]
description = "Configurable, precise and fast string parser to a rust std::time::Duration"
readme = "README.md"
license = "MIT"
keywords = ["parse", "string", "duration", "time"]
categories = ["command-line-interface", "parsing", "date-and-time"]
homepage = "https://github.com/Joining7943/fundu"
repository = "https://github.com/Joining7943/fundu"
rust-version = "1.60.0"

[lib]
bench = false

[dev-dependencies]
rstest = "0.16.0"
criterion = "0.4.0"
chrono = "0.4.23"
iai = "0.1.1"

[dev-dependencies.clap]
version = "3.2.23"
features = ["cargo", "derive"]

[target.'cfg(unix)'.dev-dependencies]
pprof = { version = "0.11.0", features = ["flamegraph", "criterion"] }

[target.'cfg(unix)'.dev-dependencies.inferno]
version = "0.11.14"

[[bench]]
name = "parse_duration_benchmark"
harness = false

[[bench]]
name = "iai_bench_time_unit_parsing"
harness = false

[[bench]]
name = "iai_bench_parsing"
harness = false

[[bench]]
name = "flamegraph_small_input"
harness = false
bench = false

[[example]]
name = "simple"
test = true

[[example]]
name = "clap_derive"
test = true

[[example]]
name = "clap_builder"
test = true
