[package]
name = "fundu"
version = "0.2.0"
edition = "2021"
authors = ["Joining7943 <joining@posteo.de>"]
description = "Configurable, precise and fast string parser to a rust std::time::Duration"
readme = "README.md"
license = "MIT"
keywords = ["parse", "string", "duration", "time"]
categories = ["command-line-interface", "parsing", "date-and-time"]
homepage = "https://github.com/Joining7943/fundu"
repository = "https://github.com/Joining7943/fundu"
rust-version = "1.60.0"

[lib]
bench = false

[dependencies]

[dev-dependencies]
rstest = "0.16.0"
criterion = "0.4.0"

[target.'cfg(unix)'.dev-dependencies]
pprof = { version = "0.11.0", features = ["flamegraph", "criterion"] }

[[bench]]
name = "parse_duration_benchmark"
harness = false

[[bench]]
name = "flamegraph_small_input"
harness = false
bench = false

[[example]]
name = "simple"
test = true
