[package]
name = "fundu"
version = "0.1.0"
edition = "2021"
authors = ["Joining7943 <joining@posteo.de>"]
description = "Configurable, precise and fast string parser to a rust std::time::Duration"
readme = "README.md"
license = "MIT"
keywords = ["parse", "string", "duration", "time"]
categories = ["command-line-interface", "parsing", "date-and-time"]
homepage = "hptts://github.com/Joining7943/fundu"
repository = "hptts://github.com/Joining7943/fundu"
rust-version = "1.60.0"

[dependencies]

[dev-dependencies]
rstest = "0.16.0"
