# spell-checker:ignore Swatinem clippy

name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    name: Build/ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2.2.0
      - name: Build
        run: cargo fmt

  build:
    name: Build/ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2.2.0
      - name: Build
        run: cargo build
        env:
          RUST_BACKTRACE: "1"

  lint:
    name: Lint/ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2.2.0
      - name: Lint
        run: cargo clippy

  test:
    name: Test/ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2.2.0
      - name: Tests
        run: cargo test
        env:
          RUST_BACKTRACE: "1"

  docs:
    name: Docs/ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2.2.0
      - name: Tests
        run: cargo doc --no-deps --document-private-items
